/**
 * calculate the subtotal, sales tax,
 * and grand total of a purchase from
 * an imaginary burger restaurant
 * 
 * modified     20210806
 * date         20210806
 * @filename    MakingPurchases.java
 * @author      Bryan Deng
 * @version     1.0
 * @see         unit 2 activity 3 content
 */

public class MakingPurchases extends javax.swing.JFrame {

    /**
     * Creates new form MakingPurchases
     */
    public MakingPurchases() {
        initComponents();

        // init label prices separately
        // to avoid interference with auto-generated code
        initLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBurgerIcon = new javax.swing.JLabel();
        lblShopName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblCheeseBurger = new javax.swing.JLabel();
        lblFountainDrink = new javax.swing.JLabel();
        lblFrenchFries = new javax.swing.JLabel();
        lblOnionRings = new javax.swing.JLabel();
        lblMilkshake = new javax.swing.JLabel();
        lblCheeseBurgerError = new javax.swing.JLabel();
        lblFrenchFriesError = new javax.swing.JLabel();
        lblOnionRingsError = new javax.swing.JLabel();
        lblFountainDrinkError = new javax.swing.JLabel();
        lblMilkshakeError = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        lblGrandTotalTxt = new javax.swing.JLabel();
        lblTaxesTxt = new javax.swing.JLabel();
        lblSubtotalTxt = new javax.swing.JLabel();
        lblSubtotalVal = new javax.swing.JLabel();
        lblTaxesVal = new javax.swing.JLabel();
        lblGrandTotalVal = new javax.swing.JLabel();
        txtCheeseBurger = new javax.swing.JTextField();
        txtFrenchFries = new javax.swing.JTextField();
        txtOnionRings = new javax.swing.JTextField();
        txtMilkshake = new javax.swing.JTextField();
        txtFountainDrink = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		// burger image citation:
		// https://bigoven-res.cloudinary.com/image/upload/t_recipe-256/smash-burger-d13992.jpg
        lblBurgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/burger.jpg"))); // NOI18N

        lblShopName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblShopName.setText("BRYAN'S BEST BURGERS");

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescription.setText("<html>Enter the amount of each item<br/>that you would like to purchase.<html>");

        lblCheeseBurger.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCheeseBurger.setText("Cheese Burger");

        lblFountainDrink.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblFountainDrink.setText("Fountain Drink");

        lblFrenchFries.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblFrenchFries.setText("French Fries");

        lblOnionRings.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblOnionRings.setText("Onion Rings");

        lblMilkshake.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMilkshake.setText("Milkshake");

        lblCheeseBurgerError.setForeground(new java.awt.Color(255, 0, 0));
        lblCheeseBurgerError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheeseBurgerError.setText(" ");

        lblFrenchFriesError.setForeground(new java.awt.Color(255, 0, 0));
        lblFrenchFriesError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFrenchFriesError.setText(" ");

        lblOnionRingsError.setForeground(new java.awt.Color(255, 0, 0));
        lblOnionRingsError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOnionRingsError.setText(" ");

        lblFountainDrinkError.setForeground(new java.awt.Color(255, 0, 0));
        lblFountainDrinkError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFountainDrinkError.setText(" ");

        lblMilkshakeError.setForeground(new java.awt.Color(255, 0, 0));
        lblMilkshakeError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMilkshakeError.setText(" ");

        btnOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrder.setText("ORDER");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        lblGrandTotalTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblGrandTotalTxt.setText("Grand Total:");

        lblTaxesTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTaxesTxt.setText("Taxes");

        lblSubtotalTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblSubtotalTxt.setText("Subtotal:");

        lblSubtotalVal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblSubtotalVal.setText("$0.00");

        lblTaxesVal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTaxesVal.setText("$0.00");

        lblGrandTotalVal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblGrandTotalVal.setText("$0.00");

        txtCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCheeseBurger.setText("0");

        txtFrenchFries.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFrenchFries.setText("0");

        txtOnionRings.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOnionRings.setText("0");

        txtMilkshake.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMilkshake.setText("0");

        txtFountainDrink.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFountainDrink.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCheeseBurgerError, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCheeseBurger)
                            .addComponent(lblFrenchFries)
                            .addComponent(lblFrenchFriesError, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOnionRings)
                            .addComponent(lblOnionRingsError, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFountainDrink)
                            .addComponent(lblFountainDrinkError, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMilkshake)
                            .addComponent(lblMilkshakeError, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubtotalTxt)
                                    .addComponent(lblTaxesTxt)
                                    .addComponent(lblGrandTotalTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTaxesVal)
                                    .addComponent(lblSubtotalVal)
                                    .addComponent(lblGrandTotalVal))
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBurgerIcon)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrenchFries, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblShopName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtOnionRings, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMilkshake, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFountainDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblBurgerIcon))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(lblShopName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDescription)))
                        .addGap(59, 59, 59)
                        .addComponent(lblCheeseBurger))
                    .addComponent(txtCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCheeseBurgerError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFrenchFries)
                            .addComponent(txtFrenchFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFrenchFriesError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotalTxt)
                            .addComponent(lblSubtotalVal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOnionRings)
                    .addComponent(lblTaxesTxt)
                    .addComponent(lblTaxesVal)
                    .addComponent(txtOnionRings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOnionRingsError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFountainDrink)
                    .addComponent(txtFountainDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFountainDrinkError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrandTotalTxt)
                            .addComponent(lblGrandTotalVal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMilkshake)
                    .addComponent(txtMilkshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMilkshakeError)
                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // constants
    private final double CHEESE_BURGER_PRICE = 5.99;
    private final double FRENCH_FRIES_PRICE = 2.49;
    private final double ONION_RINGS_PRICE = 2.99;
    private final double FOUNTAIN_DRINK_PRICE = 0.99;
    private final double MILKSHAKE_PRICE = 3.99;

    private final double TAX_RATE = 0.13;

    // init function
    private void initLabels() {
        // food prices
        lblCheeseBurger.setText(String.format("Cheese Burger ($%.2f):", CHEESE_BURGER_PRICE));
        lblFrenchFries.setText(String.format("French Fries ($%.2f):", FRENCH_FRIES_PRICE));
        lblOnionRings.setText(String.format("Onion Rings ($%.2f):", ONION_RINGS_PRICE));
        lblFountainDrink.setText(String.format("Fountain Drink ($%.2f):", FOUNTAIN_DRINK_PRICE));
        lblMilkshake.setText(String.format("Milkshake ($%.2f):", MILKSHAKE_PRICE));

        // tax rate
        lblTaxesTxt.setText(String.format("Taxes (%.2f%%):", TAX_RATE));
    }

    private int handleInput(javax.swing.JTextField input, javax.swing.JLabel errorField) {
        int parsed;
        String strVal = input.getText().trim();
        
        // handle empty input
        if (strVal.isEmpty()){
            strVal = "0";
            input.setText("0");
        }
        
        try {
            parsed = Integer.parseInt(strVal);
            
            if (parsed < 0) {
                errorField.setText("Please enter a positive integer.");
                return -1;
            }
            
            errorField.setText(" ");
        } catch (Exception e) {
            // Exception from Integer.parseInt()
            errorField.setText("Please enter a positive integer.");
            return -1;
        }
        
        errorField.setText(" ");
        return parsed;
    }

    private String formatPrice(double price) {
        return String.format("$%.2f", Math.round(price * 100.0) / 100.0);
    }

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed

        int cheeseBurgerCnt = handleInput(txtCheeseBurger, lblCheeseBurgerError);
        int frenchFriesCnt = handleInput(txtFrenchFries, lblFrenchFriesError);
        int onionRingsCnt = handleInput(txtOnionRings, lblOnionRingsError);
        int fountainDrinkCnt = handleInput(txtFountainDrink, lblFountainDrinkError);
        int milkshakeCnt = handleInput(txtMilkshake, lblMilkshakeError);

        if (cheeseBurgerCnt == -1 || frenchFriesCnt == -1 || onionRingsCnt == -1 
                || fountainDrinkCnt == -1 || milkshakeCnt == -1) {
            lblSubtotalVal.setText("ERROR");
            lblTaxesVal.setText("ERROR");
            lblGrandTotalVal.setText("ERROR");
        } else {
            double subtotal = CHEESE_BURGER_PRICE * cheeseBurgerCnt + 
                    FRENCH_FRIES_PRICE * frenchFriesCnt + 
                    ONION_RINGS_PRICE * onionRingsCnt + 
                    FOUNTAIN_DRINK_PRICE * fountainDrinkCnt + 
                    MILKSHAKE_PRICE * milkshakeCnt;
            double taxes = TAX_RATE * subtotal;
            double grandTotal = subtotal + taxes;

            lblSubtotalVal.setText(formatPrice(subtotal));
            lblTaxesVal.setText(formatPrice(taxes));
            lblGrandTotalVal.setText(formatPrice(grandTotal));
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingPurchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel lblBurgerIcon;
    private javax.swing.JLabel lblCheeseBurger;
    private javax.swing.JLabel lblCheeseBurgerError;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFountainDrink;
    private javax.swing.JLabel lblFountainDrinkError;
    private javax.swing.JLabel lblFrenchFries;
    private javax.swing.JLabel lblFrenchFriesError;
    private javax.swing.JLabel lblGrandTotalTxt;
    private javax.swing.JLabel lblGrandTotalVal;
    private javax.swing.JLabel lblMilkshake;
    private javax.swing.JLabel lblMilkshakeError;
    private javax.swing.JLabel lblOnionRings;
    private javax.swing.JLabel lblOnionRingsError;
    private javax.swing.JLabel lblShopName;
    private javax.swing.JLabel lblSubtotalTxt;
    private javax.swing.JLabel lblSubtotalVal;
    private javax.swing.JLabel lblTaxesTxt;
    private javax.swing.JLabel lblTaxesVal;
    private javax.swing.JTextField txtCheeseBurger;
    private javax.swing.JTextField txtFountainDrink;
    private javax.swing.JTextField txtFrenchFries;
    private javax.swing.JTextField txtMilkshake;
    private javax.swing.JTextField txtOnionRings;
    // End of variables declaration//GEN-END:variables
}
