
/**
 * number system converters for: 
 * - decimal to binary and back
 * - decimal to hexadecimal and back
 *
 * modified 20210822 
 * date     20210822
 *
 * @filename BinaryHexadecimalConverters.java
 * @author Bryan Deng
 * @version 1.0
 * @see unit 4 activity 3 content
 */
import java.awt.Color;

public class BinaryHexadecimalConverters extends javax.swing.JFrame {

    /**
     * Creates new form BinaryHexadecimalConverters
     */
    public BinaryHexadecimalConverters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDecBinTitle = new javax.swing.JLabel();
        lblDecBinPrompt = new javax.swing.JLabel();
        txtDecBin = new javax.swing.JTextField();
        btnDecBin = new javax.swing.JButton();
        lblDecBinOutput = new javax.swing.JLabel();
        txtBinDec = new javax.swing.JTextField();
        lblBinDecPrompt = new javax.swing.JLabel();
        btnBinDec = new javax.swing.JButton();
        lblBinDecOutput = new javax.swing.JLabel();
        lblDecHexTitle = new javax.swing.JLabel();
        lblHexDecPrompt = new javax.swing.JLabel();
        txtHexDec = new javax.swing.JTextField();
        btnHexDec = new javax.swing.JButton();
        lblHexDecOutput = new javax.swing.JLabel();
        lblDecHexOutput = new javax.swing.JLabel();
        btnDecHex = new javax.swing.JButton();
        txtDecHex = new javax.swing.JTextField();
        lblDecHexPrompt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setText("~ ~ NUMBER SYSTEMS ~ ~");

        lblDecBinTitle.setText("Decimal and Binary");

        lblDecBinPrompt.setText("Enter a decimal number:");

        btnDecBin.setText("To Binary");
        btnDecBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecBinActionPerformed(evt);
            }
        });

        lblDecBinOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDecBinOutput.setText("...");

        lblBinDecPrompt.setText("Enter a binary number:");

        btnBinDec.setText("To Decimal");
        btnBinDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinDecActionPerformed(evt);
            }
        });

        lblBinDecOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBinDecOutput.setText("...");

        lblDecHexTitle.setText("Decimal and Hexadecimal");

        lblHexDecPrompt.setText("Enter a hexidecimal number:");

        btnHexDec.setText("To Decimal");
        btnHexDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexDecActionPerformed(evt);
            }
        });

        lblHexDecOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHexDecOutput.setText("...");

        lblDecHexOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDecHexOutput.setText("...");

        btnDecHex.setText("To Hexidecimal");
        btnDecHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecHexActionPerformed(evt);
            }
        });

        lblDecHexPrompt.setText("Enter a decimal number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDecHexPrompt)
                                    .addComponent(lblHexDecPrompt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDecHex, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDecHex))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtHexDec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHexDec)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHexDecOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                    .addComponent(lblDecHexOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDecBinPrompt)
                                            .addComponent(lblBinDecPrompt))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtBinDec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBinDec))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtDecBin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDecBin))
                                            .addComponent(lblDecBinTitle))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDecBinOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                    .addComponent(lblBinDecOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblDecHexTitle)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblDecBinTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDecBinPrompt))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDecBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDecBin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBinDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBinDec)
                            .addComponent(lblBinDecPrompt)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDecBinOutput))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblBinDecOutput)))
                .addGap(18, 18, 18)
                .addComponent(lblDecHexTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDecHexPrompt)
                    .addComponent(txtDecHex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecHex)
                    .addComponent(lblDecHexOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHexDecPrompt)
                    .addComponent(txtHexDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHexDec)
                    .addComponent(lblHexDecOutput))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecBinActionPerformed
        int decimal;
        try {
            decimal = inputInt(txtDecBin, lblDecBinOutput);
        } catch (Exception e) {
            return;
        }

        String binary = Integer.toBinaryString(decimal);
        lblDecBinOutput.setForeground(Color.black);
        lblDecBinOutput.setText(binary);
    }//GEN-LAST:event_btnDecBinActionPerformed

    private void btnBinDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinDecActionPerformed
        String binary = txtBinDec.getText().trim();

        int decimal;
        try {
            decimal = Integer.parseInt(binary, 2);
        } catch (Exception e) {
            lblBinDecOutput.setForeground(Color.red);
            lblBinDecOutput.setText("Error");
            return;
        }

        lblBinDecOutput.setForeground(Color.black);
        lblBinDecOutput.setText(String.valueOf(decimal));
    }//GEN-LAST:event_btnBinDecActionPerformed

    private void btnDecHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecHexActionPerformed
        int decimal;
        try {
            decimal = inputInt(txtDecHex, lblDecHexOutput);
        } catch (Exception e) {
            return;
        }

        String hexadecimal = Integer.toHexString(decimal);
        lblDecHexOutput.setForeground(Color.black);
        lblDecHexOutput.setText(hexadecimal);
    }//GEN-LAST:event_btnDecHexActionPerformed

    private void btnHexDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexDecActionPerformed
        String hexadecimal = txtHexDec.getText().trim();

        int decimal;
        try {
            decimal = Integer.parseInt(hexadecimal, 16);
        } catch (Exception e) {
            lblHexDecOutput.setForeground(Color.red);
            lblHexDecOutput.setText("Error");
            return;
        }
        System.out.println("through");

        lblHexDecOutput.setForeground(Color.black);
        lblHexDecOutput.setText(String.valueOf(decimal));
    }//GEN-LAST:event_btnHexDecActionPerformed

    private int inputInt(javax.swing.JTextField input, javax.swing.JLabel output) throws Exception {
        String inputString = input.getText().trim();

        int parsed;
        try {
            parsed = Integer.parseInt(inputString);
            return parsed;
        } catch (Exception e) {
            output.setForeground(Color.red);
            output.setText("Error");
            throw new Exception();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BinaryHexadecimalConverters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BinaryHexadecimalConverters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BinaryHexadecimalConverters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BinaryHexadecimalConverters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BinaryHexadecimalConverters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBinDec;
    private javax.swing.JButton btnDecBin;
    private javax.swing.JButton btnDecHex;
    private javax.swing.JButton btnHexDec;
    private javax.swing.JLabel lblBinDecOutput;
    private javax.swing.JLabel lblBinDecPrompt;
    private javax.swing.JLabel lblDecBinOutput;
    private javax.swing.JLabel lblDecBinPrompt;
    private javax.swing.JLabel lblDecBinTitle;
    private javax.swing.JLabel lblDecHexOutput;
    private javax.swing.JLabel lblDecHexPrompt;
    private javax.swing.JLabel lblDecHexTitle;
    private javax.swing.JLabel lblHexDecOutput;
    private javax.swing.JLabel lblHexDecPrompt;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBinDec;
    private javax.swing.JTextField txtDecBin;
    private javax.swing.JTextField txtDecHex;
    private javax.swing.JTextField txtHexDec;
    // End of variables declaration//GEN-END:variables
}
