
/**
 * calculate income tax due
 * based on salary
 *
 * modified     20210806
 * date         20210806
 *
 * @filename IncomeTax.java
 * @author Bryan Deng
 * @version 1.0
 * @see unit 2 activity 2 content
 */
public class IncomeTax extends javax.swing.JFrame {

    /**
     * Creates new form IncomeTax
     */
    public IncomeTax() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIncomeTaxCalculator = new javax.swing.JLabel();
        lblSalaryTxt = new javax.swing.JLabel();
        lblTaxDueTxt = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        lblSalaryVal = new javax.swing.JTextField();
        lblSalaryError = new javax.swing.JLabel();
        lblTaxDueVal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIncomeTaxCalculator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIncomeTaxCalculator.setText("INCOME TAX CALCULATOR");

        lblSalaryTxt.setText("Salary:");

        lblTaxDueTxt.setText("Income Tax Due:");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblSalaryVal.setText("0.00");

        lblSalaryError.setForeground(new java.awt.Color(255, 0, 0));
        lblSalaryError.setText(" ");

        lblTaxDueVal.setText("$0.00");

        jLabel1.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSalaryError, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTaxDueTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTaxDueVal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblIncomeTaxCalculator)
                                .addComponent(btnCalculate)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSalaryTxt)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSalaryVal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIncomeTaxCalculator)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalaryTxt)
                    .addComponent(lblSalaryVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(lblSalaryError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxDueTxt)
                    .addComponent(lblTaxDueVal))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private double handleInput(javax.swing.JTextField input, javax.swing.JLabel errorField) {
        double parsed;
        String strVal = input.getText().trim();

        if (strVal.isEmpty()) {
            strVal = "0.00";
            input.setText("0.00");
        }

        try {
            parsed = Double.parseDouble(strVal);

            if (parsed < 0) {
                errorField.setText("Please enter a positive integer.");
                return -1;
            }

            errorField.setText(" ");
        } catch (Exception e) {
            // Exception from Integer.parseInt()
            errorField.setText("Please enter a positive integer.");
            return -1;
        }

        errorField.setText(" ");
        return parsed;
    }

    private String formatPrice(double price) {
        return String.format("$%.2f", Math.round(price * 100.0) / 100.0);
    }

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        final int[] TAX_BRACKETS = {49020, 49020, 53939, 64533};
        final double[] TAX_RATES = {0.15, 0.205, 0.26, 0.29, 0.33};
        final int BRACKET_CNT = TAX_BRACKETS.length;

        double salary = handleInput(lblSalaryVal, lblSalaryError);
        if (salary == -1.0) {
            lblTaxDueVal.setText("ERROR");
        } else {
            double taxDue = 0.0;
            for (int bracket = 0; bracket < BRACKET_CNT; bracket++) {
                if (salary >= TAX_BRACKETS[bracket]) {
                    salary -= TAX_BRACKETS[bracket];
                    taxDue += TAX_RATES[bracket] * TAX_BRACKETS[bracket];
                } else if (salary != 0) {
                    taxDue += TAX_RATES[bracket] * salary;
                    salary = 0;
                }
            }

            if (salary != 0) {
                taxDue += TAX_RATES[TAX_RATES.length - 1] * salary;
            }

            lblTaxDueVal.setText(formatPrice(taxDue));
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncomeTax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIncomeTaxCalculator;
    private javax.swing.JLabel lblSalaryError;
    private javax.swing.JLabel lblSalaryTxt;
    private javax.swing.JTextField lblSalaryVal;
    private javax.swing.JLabel lblTaxDueTxt;
    private javax.swing.JLabel lblTaxDueVal;
    // End of variables declaration//GEN-END:variables
}
