
/**
 * calculate the subtotal, sales tax,
 * and grand total of a purchase consisting
 * of USB storage devices, keyboards,
 * and computer mice
 *
 * modified     20210806
 * date         20210806
 *
 * @filename Water.java
 * @author Bryan Deng
 * @version 1.0
 * @see unit 2 activity 2 content
 */
public class Shopping extends javax.swing.JFrame {

    /**
     * Creates new form Shopping
     */
    public Shopping() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblSubtotalTxt = new javax.swing.JLabel();
        lblUsbTxt = new javax.swing.JLabel();
        lblKeyboardTxt = new javax.swing.JLabel();
        lblMouseTxt = new javax.swing.JLabel();
        lblUsbError = new javax.swing.JLabel();
        lblKeyboardError = new javax.swing.JLabel();
        lblMouseError = new javax.swing.JLabel();
        txtKeyboardVal = new javax.swing.JTextField();
        txtMouseVal = new javax.swing.JTextField();
        lblShoppingCartTxt = new javax.swing.JLabel();
        lblTaxTxt = new javax.swing.JLabel();
        lblGrandTotalTxt = new javax.swing.JLabel();
        lblSubtotalVal = new javax.swing.JLabel();
        lblTaxVal = new javax.swing.JLabel();
        lblGrandTotalVal = new javax.swing.JLabel();
        btnCalculateTotal = new javax.swing.JButton();
        txtUsbVal = new javax.swing.JTextField();

        jLabel3.setText("$0.00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSubtotalTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubtotalTxt.setText("Subtotal:");

        lblUsbTxt.setText("USB Storage Device(s):");

        lblKeyboardTxt.setText("Keyboard(s)");

        lblMouseTxt.setText("Computer Mouse(s)");

        lblUsbError.setForeground(new java.awt.Color(255, 0, 0));
        lblUsbError.setText(" ");

        lblKeyboardError.setForeground(new java.awt.Color(255, 0, 0));
        lblKeyboardError.setText(" ");

        lblMouseError.setForeground(new java.awt.Color(255, 0, 0));
        lblMouseError.setText(" ");

        txtKeyboardVal.setText("0");

        txtMouseVal.setText("0");

        lblShoppingCartTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblShoppingCartTxt.setText("SHOPPING CART");

        lblTaxTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTaxTxt.setText("Taxes:");

        lblGrandTotalTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGrandTotalTxt.setText("Grand Total:");

        lblSubtotalVal.setText("$0.00");

        lblTaxVal.setText("$0.00");

        lblGrandTotalVal.setText("$0.00");

        btnCalculateTotal.setText("Calculate");
        btnCalculateTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateTotalActionPerformed(evt);
            }
        });

        txtUsbVal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTaxTxt)
                            .addComponent(lblSubtotalTxt)
                            .addComponent(lblGrandTotalTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtotalVal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTaxVal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGrandTotalVal, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMouseTxt)
                            .addComponent(lblKeyboardTxt)
                            .addComponent(lblUsbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShoppingCartTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKeyboardVal)
                            .addComponent(txtMouseVal)
                            .addComponent(txtUsbVal, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsbError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(lblKeyboardError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMouseError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(btnCalculateTotal)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblShoppingCartTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsbTxt)
                    .addComponent(txtUsbVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsbError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeyboardTxt)
                    .addComponent(txtKeyboardVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKeyboardError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMouseTxt)
                    .addComponent(txtMouseVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMouseError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnCalculateTotal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotalTxt)
                    .addComponent(lblSubtotalVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxTxt)
                    .addComponent(lblTaxVal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrandTotalTxt)
                    .addComponent(lblGrandTotalVal))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int handleInput(javax.swing.JTextField input, javax.swing.JLabel errorField) {
        int parsed;
        String strVal = input.getText().trim();

        if (strVal.isEmpty()) {
            strVal = "0";
            input.setText("0");
        }

        try {
            parsed = Integer.parseInt(strVal);

            if (parsed < 0) {
                errorField.setText("Please enter a positive integer.");
                return -1;
            }

            errorField.setText(" ");
        } catch (Exception e) {
            // Exception from Integer.parseInt()
            errorField.setText("Please enter a positive integer.");
            return -1;
        }

        errorField.setText(" ");
        return parsed;
    }

    private String formatPrice(double price) {
        return String.format("$%.2f", Math.round(price * 100.0) / 100.0);
    }

    private void btnCalculateTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateTotalActionPerformed
        final double USB_PRICE = 19.99;
        final double KEYBOARD_PRICE = 49.99;
        final double MOUSE_PRICE = 25.99;
        final double TAX_RATE = 0.13;

        int usbCnt = handleInput(txtUsbVal, lblUsbError);
        int keyboardCnt = handleInput(txtKeyboardVal, lblKeyboardError);
        int mouseCnt = handleInput(txtMouseVal, lblMouseError);

        if (usbCnt == -1 || keyboardCnt == -1 || mouseCnt == -1) {
            lblSubtotalVal.setText("ERROR");
            lblTaxVal.setText("ERROR");
            lblGrandTotalVal.setText("ERROR");
        } else {
            double usbCost = USB_PRICE * usbCnt;
            double keyboardCost = KEYBOARD_PRICE * keyboardCnt;
            double mouseCost = MOUSE_PRICE * mouseCnt;

            double subtotal = usbCost + keyboardCost + mouseCost;
            double tax = subtotal * TAX_RATE;
            double grandTotal = subtotal + tax;

            lblSubtotalVal.setText(formatPrice(subtotal));
            lblTaxVal.setText(formatPrice(tax));
            lblGrandTotalVal.setText(formatPrice(grandTotal));
        }
    }//GEN-LAST:event_btnCalculateTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shopping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateTotal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGrandTotalTxt;
    private javax.swing.JLabel lblGrandTotalVal;
    private javax.swing.JLabel lblKeyboardError;
    private javax.swing.JLabel lblKeyboardTxt;
    private javax.swing.JLabel lblMouseError;
    private javax.swing.JLabel lblMouseTxt;
    private javax.swing.JLabel lblShoppingCartTxt;
    private javax.swing.JLabel lblSubtotalTxt;
    private javax.swing.JLabel lblSubtotalVal;
    private javax.swing.JLabel lblTaxTxt;
    private javax.swing.JLabel lblTaxVal;
    private javax.swing.JLabel lblUsbError;
    private javax.swing.JLabel lblUsbTxt;
    private javax.swing.JTextField txtKeyboardVal;
    private javax.swing.JTextField txtMouseVal;
    private javax.swing.JTextField txtUsbVal;
    // End of variables declaration//GEN-END:variables
}
