/**
 * calculate the tons of water used in
 * manufacturing computer/monitor
 * combos
 * 
 * modified     20210806
 * date         20210806
 * @filename    Water.java
 * @author      Bryan Deng
 * @version     1.0
 * @see         unit 2 activity 2 content
 */

public class Water extends javax.swing.JFrame {

    /**
     * Creates new form Water
     */
    public Water() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComputerMonitorCombos = new javax.swing.JLabel();
        txtComputerMonitorCombos = new javax.swing.JTextField();
        btnCalculateWaterUsage = new javax.swing.JButton();
        lblWaterUsedAns = new javax.swing.JLabel();
        lblWaterUsedTxt = new javax.swing.JLabel();
        lblErrorField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblComputerMonitorCombos.setText("Computer/Monitor Combos:");

        btnCalculateWaterUsage.setText("Calculate");
        btnCalculateWaterUsage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateWaterUsageActionPerformed(evt);
            }
        });

        lblWaterUsedTxt.setText("Water Used:");

        lblErrorField.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorField.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalculateWaterUsage)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblWaterUsedAns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblWaterUsedTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblErrorField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblComputerMonitorCombos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addComponent(txtComputerMonitorCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputerMonitorCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComputerMonitorCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorField)
                .addGap(18, 18, 18)
                .addComponent(btnCalculateWaterUsage)
                .addGap(18, 18, 18)
                .addComponent(lblWaterUsedTxt)
                .addGap(18, 18, 18)
                .addComponent(lblWaterUsedAns)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCalculateWaterUsageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateWaterUsageActionPerformed
        final double WATER_NEEDED = 1.5;
        
        int computerMonitorCombos;
        
        try {
            computerMonitorCombos = Integer.parseInt(txtComputerMonitorCombos.getText().trim());
            
            if (computerMonitorCombos < 0) {
                lblErrorField.setText("Please enter a positive integer.");
            } else {
                double waterUsed = WATER_NEEDED * computerMonitorCombos;
                
                lblWaterUsedAns.setText(String.valueOf(waterUsed) + " ton(s)");
                lblErrorField.setText("");
            }
        } catch (Exception e) {
            // Exception from Integer.parseInt()
            lblErrorField.setText("Please enter a positive integer.");
            lblWaterUsedAns.setText("ERROR");
        }
    }//GEN-LAST:event_btnCalculateWaterUsageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Water.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Water.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Water.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Water.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Water().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateWaterUsage;
    private javax.swing.JLabel lblComputerMonitorCombos;
    private javax.swing.JLabel lblErrorField;
    private javax.swing.JLabel lblWaterUsedAns;
    private javax.swing.JLabel lblWaterUsedTxt;
    private javax.swing.JTextField txtComputerMonitorCombos;
    // End of variables declaration//GEN-END:variables
}
