
/**
 * using builtin String methods
 *
 * modified     20210821
 * date         20210821
 *
 * @filename UsingStringMethods.java
 * @author Bryan Deng
 * @version 1.0
 * @see unit 2 activity 4 content
 */
import java.awt.Color;

public class UsingStringMethods extends javax.swing.JFrame {

    /**
     * Creates new form UsingStringMethods
     */
    public UsingStringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblLengthPrompt = new javax.swing.JLabel();
        txtUppercase = new javax.swing.JTextField();
        btnLength = new javax.swing.JButton();
        lblLengthOutput = new javax.swing.JLabel();
        lblUppercasePrompt = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        btnUppercase = new javax.swing.JButton();
        lblUppercaseOutput = new javax.swing.JLabel();
        lblCharAtPrompt = new javax.swing.JLabel();
        txtCharAt = new javax.swing.JTextField();
        btnCharAt = new javax.swing.JButton();
        lblCharAtOutput = new javax.swing.JLabel();
        lblEqualsPrompt = new javax.swing.JLabel();
        txtEquals1 = new javax.swing.JTextField();
        txtEquals2 = new javax.swing.JTextField();
        btnEquals = new javax.swing.JButton();
        lblEqualsOutput = new javax.swing.JLabel();
        lblContainsPrompt = new javax.swing.JLabel();
        txtContainsString = new javax.swing.JTextField();
        txtContainsChar = new javax.swing.JTextField();
        btnContains = new javax.swing.JButton();
        lblContainsOutput = new javax.swing.JLabel();
        lblSubstringPrompt = new javax.swing.JLabel();
        txtSubstring = new javax.swing.JTextField();
        btnSubstring = new javax.swing.JButton();
        lblSubstringOutput = new javax.swing.JLabel();
        lblReplaceAllPrompt = new javax.swing.JLabel();
        txtReplaceAll = new javax.swing.JTextField();
        btnReplaceAll = new javax.swing.JButton();
        lblReplaceAllOutput = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblTitle.setText("Spectacular String Software");

        lblLengthPrompt.setText("Enter a String. The program will output the number of characters in the String:");

        btnLength.setText("Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        lblLengthOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLengthOutput.setText("...");

        lblUppercasePrompt.setText("Enter a String using lowercase letters. The program will output the String in all capital letters:");

        btnUppercase.setText("All Caps");
        btnUppercase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppercaseActionPerformed(evt);
            }
        });

        lblUppercaseOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUppercaseOutput.setText("...");

        lblCharAtPrompt.setText("Enter a String. The program will output the character at the 4th spot:");

        btnCharAt.setText("4th Spot");
        btnCharAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCharAtActionPerformed(evt);
            }
        });

        lblCharAtOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCharAtOutput.setText("...");

        lblEqualsPrompt.setText("Enter two Strings. The program will output whether or not they are identical:");

        btnEquals.setText("Identical?");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        lblEqualsOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEqualsOutput.setText("...");

        lblContainsPrompt.setText("Enter a String and a letter. The program will output whether or not the letter is found in the String:");

        btnContains.setText("Letter Found?");
        btnContains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContainsActionPerformed(evt);
            }
        });

        lblContainsOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContainsOutput.setText("...");

        lblSubstringPrompt.setText("Enter a String that is at least 8 characters long. The program will output characters 4 to 6:");

        btnSubstring.setText("Characters 4 to 6");
        btnSubstring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubstringActionPerformed(evt);
            }
        });

        lblSubstringOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubstringOutput.setText("...");

        lblReplaceAllPrompt.setText("Enter a String that contains at least one \"a\". The program will replace all occurences of the letter \"a\" with \"x\":");

        btnReplaceAll.setText("Replaces \"a\"");
        btnReplaceAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceAllActionPerformed(evt);
            }
        });

        lblReplaceAllOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReplaceAllOutput.setText("...");

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtReplaceAll, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnReplaceAll)
                        .addGap(51, 51, 51)
                        .addComponent(lblReplaceAllOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblReplaceAllPrompt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSubstring, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnSubstring)
                        .addGap(18, 18, 18)
                        .addComponent(lblSubstringOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSubstringPrompt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtContainsString, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtContainsChar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnContains)
                        .addGap(34, 34, 34)
                        .addComponent(lblContainsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblContainsPrompt)
                    .addComponent(lblEqualsPrompt)
                    .addComponent(lblCharAtPrompt)
                    .addComponent(lblUppercasePrompt)
                    .addComponent(lblTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(btnLength)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLengthOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblLengthPrompt))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(txtEquals1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEquals2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(btnEquals)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEqualsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCharAt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(btnCharAt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCharAtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtUppercase, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(btnUppercase)
                            .addGap(58, 58, 58)
                            .addComponent(lblUppercaseOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLengthPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLength)
                    .addComponent(lblLengthOutput)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUppercasePrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUppercase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUppercase)
                    .addComponent(lblUppercaseOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCharAtPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCharAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharAt)
                    .addComponent(lblCharAtOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEqualsPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEquals1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEquals2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquals)
                    .addComponent(lblEqualsOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContainsPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContainsString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContainsChar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContains)
                    .addComponent(lblContainsOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubstringPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubstring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubstring)
                    .addComponent(lblSubstringOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReplaceAllPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReplaceAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReplaceAll)
                    .addComponent(lblReplaceAllOutput))
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUppercaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppercaseActionPerformed
        String input = txtUppercase.getText();

        String output = input.toUpperCase();
        lblUppercaseOutput.setText(output);
    }//GEN-LAST:event_btnUppercaseActionPerformed

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
        String input = txtLength.getText();

        String output = String.valueOf(input.length());
        lblLengthOutput.setText(output);
    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnCharAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharAtActionPerformed
        final int index = 4;

        String input = txtCharAt.getText();

        if (input.length() < 5) {
            lblCharAtOutput.setForeground(Color.red);
            lblCharAtOutput.setText("Error");
            return;
        }

        String output = String.valueOf(input.charAt(index));
        lblCharAtOutput.setForeground(Color.black);
        lblCharAtOutput.setText(output);
    }//GEN-LAST:event_btnCharAtActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        String input1 = txtEquals1.getText();
        String input2 = txtEquals2.getText();

        String output = input1.equals(input2) ? "yes" : "no";
        lblEqualsOutput.setText(output);
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnContainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContainsActionPerformed
		// read char input as String because
		// .contains takes a String as its parameter.
		// avoids unecessary conversion to char then
		// back to String
        String inputString = txtContainsString.getText();
        String inputChar = txtContainsChar.getText();

        if (inputChar.length() != 1) {
            lblContainsOutput.setForeground(Color.red);
            lblContainsOutput.setText("Error");
            return;
        }

        String output = inputString.contains(inputChar) ? "yes" : "no";
        lblContainsOutput.setForeground(Color.black);
        lblContainsOutput.setText(output);
    }//GEN-LAST:event_btnContainsActionPerformed

    private void btnSubstringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubstringActionPerformed
        final int start = 4, end = 6;

        String input = txtSubstring.getText();

        if (input.length() < 8) {
            lblSubstringOutput.setForeground(Color.red);
            lblSubstringOutput.setText("Error");
            return;
        }

        String output = input.substring(start, end + 1);
        lblSubstringOutput.setForeground(Color.black);
        lblSubstringOutput.setText(output);
    }//GEN-LAST:event_btnSubstringActionPerformed

    private void btnReplaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceAllActionPerformed
        final String char1 = "a", char2 = "z";

        String input = txtReplaceAll.getText();

        String output = input.replaceAll(char1, char2);
        lblReplaceAllOutput.setText(output);
    }//GEN-LAST:event_btnReplaceAllActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        final String emptyOutput = "...";
        final String emptyInput = "";

        lblLengthOutput.setText(emptyOutput);
        txtLength.setText(emptyInput);

        lblUppercaseOutput.setText(emptyOutput);
        txtUppercase.setText(emptyInput);

        lblCharAtOutput.setForeground(Color.black);
        lblCharAtOutput.setText(emptyOutput);
        txtCharAt.setText(emptyInput);

        lblEqualsOutput.setText(emptyOutput);
        txtEquals1.setText(emptyInput);
        txtEquals2.setText(emptyInput);

        lblContainsOutput.setForeground(Color.black);
        lblContainsOutput.setText(emptyOutput);
        txtContainsString.setText(emptyInput);
        txtContainsChar.setText(emptyInput);

        lblSubstringOutput.setForeground(Color.black);
        lblSubstringOutput.setText(emptyOutput);
        txtSubstring.setText(emptyInput);

        lblReplaceAllOutput.setText(emptyOutput);
        txtReplaceAll.setText(emptyInput);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsingStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsingStringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharAt;
    private javax.swing.JButton btnContains;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnReplaceAll;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubstring;
    private javax.swing.JButton btnUppercase;
    private javax.swing.JLabel lblCharAtOutput;
    private javax.swing.JLabel lblCharAtPrompt;
    private javax.swing.JLabel lblContainsOutput;
    private javax.swing.JLabel lblContainsPrompt;
    private javax.swing.JLabel lblEqualsOutput;
    private javax.swing.JLabel lblEqualsPrompt;
    private javax.swing.JLabel lblLengthOutput;
    private javax.swing.JLabel lblLengthPrompt;
    private javax.swing.JLabel lblReplaceAllOutput;
    private javax.swing.JLabel lblReplaceAllPrompt;
    private javax.swing.JLabel lblSubstringOutput;
    private javax.swing.JLabel lblSubstringPrompt;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUppercaseOutput;
    private javax.swing.JLabel lblUppercasePrompt;
    private javax.swing.JTextField txtCharAt;
    private javax.swing.JTextField txtContainsChar;
    private javax.swing.JTextField txtContainsString;
    private javax.swing.JTextField txtEquals1;
    private javax.swing.JTextField txtEquals2;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtReplaceAll;
    private javax.swing.JTextField txtSubstring;
    private javax.swing.JTextField txtUppercase;
    // End of variables declaration//GEN-END:variables
}
